import "./globals.css";
import type { Metadata } from "next";
import { Golos_Text } from "next/font/google";

import { getAccessCode } from "@/lib/axios";
import Hero from "@/components/hero";
import { Toaster } from "@/components/ui/toaster";
import Footer from "@/components/footer";

const golos = Golos_Text({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TOOL",
  // description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  await getAccessCode();

  return (
    <html lang="en" className={golos.className}>
      <body className="dark bg-cover">
        <Hero />
        {children}
        <Toaster />
        <Footer />
      </body>
    </html>
  );
}
