import "./globals.css";
import type { Metadata } from "next";
import { Golos_Text } from "next/font/google";

import { getAccessCode } from "@/lib/axios";
import TwitterLogo from "@/public/twitter.svg";
import InstagramLogo from "@/public/instagram.svg";
import FacebookLogo from "@/public/facebook.svg";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import Image from "next/image";

const golos = Golos_Text({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TOOL",
  // description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  await getAccessCode();

  return (
    <html lang="en" className={golos.className}>
      <body className="dark bg-cover">{children}</body>
      <footer className="dark flex flex-col-reverse content-center items-center justify-between p-4 align-middle md:flex-row">
        <span>© Juan Builes 2023</span>
        <div>
          <Button variant="ghost" asChild>
            <Link target="_blank" href="https://twitter.com/Tool">
              <Image src={TwitterLogo} alt="Twitter Logo" />
            </Link>
          </Button>
          <Button variant="ghost" asChild>
            <Link target="_blank" href="https://www.instagram.com/toolmusic/">
              <Image src={InstagramLogo} alt="Instagram Logo" />
            </Link>
          </Button>
          <Button variant="ghost" asChild>
            <Link target="_blank" href="https://www.facebook.com/ToolMusic/">
              <Image src={FacebookLogo} alt="Facebook Logo" />
            </Link>
          </Button>
        </div>
      </footer>
    </html>
  );
}
