import { getAccessCode } from "@/lib/axios";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Musician Info",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  await getAccessCode();

  return (
    <html lang="en">
      <body className="dark bg-primary bg-cover">{children}</body>
    </html>
  );
}
